=== ksmyth/UDM/src/Uml/Uml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?udm interface="Uml" version="2.04"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 elementFormDefault="qualified" 
>
<!-- generated on Thu Nov 05 17:19:40 2015 -->


	<xsd:complexType name="CompositionChildRoleType">
		<xsd:attribute name="max" type="xsd:long" use="required"/>
		<xsd:attribute name="min" type="xsd:long" use="required"/>
		<xsd:attribute name="isNavigable" type="xsd:boolean" default="true"/>
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="target" type="xsd:IDREF" use="required"/>
		<xsd:attribute name="_id" type="xsd:ID"/>
		<xsd:attribute name="_archetype" type="xsd:IDREF"/>
		<xsd:attribute name="_derived" type="xsd:IDREFS"/>
		<xsd:attribute name="_instances" type="xsd:IDREFS"/>
		<xsd:attribute name="_desynched_atts" type="xsd:string"/>
		<xsd:attribute name="_real_archetype" type="xsd:boolean"/>
		<xsd:attribute name="_subtype" type="xsd:boolean"/>
	</xsd:complexType>

	<xsd:complexType name="GenericRoleType">
		<xsd:attribute name="isNavigable" type="xsd:boolean" default="true"/>
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="_id" type="xsd:ID"/>
		<xsd:attribute name="_archetype" type="xsd:IDREF"/>
		<xsd:attribute name="_derived" type="xsd:IDREFS"/>
		<xsd:attribute name="_instances" type="xsd:IDREFS"/>
		<xsd:attribute name="_desynched_atts" type="xsd:string"/>
		<xsd:attribute name="_real_archetype" type="xsd:boolean"/>
		<xsd:attribute name="_subtype" type="xsd:boolean"/>
	</xsd:complexType>

	<xsd:complexType name="CompositionParentRoleType">
		<xsd:attribute name="isNavigable" type="xsd:boolean" default="true"/>
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="target" type="xsd:IDREF" use="required"/>
		<xsd:attribute name="_id" type="xsd:ID"/>
		<xsd:attribute name="_archetype" type="xsd:IDREF"/>
		<xsd:attribute name="_derived" type="xsd:IDREFS"/>
		<xsd:attribute name="_instances" type="xsd:IDREFS"/>
		<xsd:attribute name="_desynched_atts" type="xsd:string"/>
		<xsd:attribute name="_real_archetype" type="xsd:boolean"/>
		<xsd:attribute name="_subtype" type="xsd:boolean"/>
	</xsd:complexType>

	<xsd:complexType name="AssociationRoleType">
		<xsd:attribute name="isNavigable" type="xsd:boolean" default="true"/>
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="max" type="xsd:long" use="required"/>
		<xsd:attribute name="min" type="xsd:long" use="required"/>
		<xsd:attribute name="isPrimary" type="xsd:boolean" default="false"/>
		<xsd:attribute name="rp_helper_user" type="xsd:IDREF"/>
		<xsd:attribute name="rp_helper" type="xsd:IDREF"/>
		<xsd:attribute name="target" type="xsd:IDREF" use="required"/>
		<xsd:attribute name="_id" type="xsd:ID"/>
		<xsd:attribute name="_archetype" type="xsd:IDREF"/>
		<xsd:attribute name="_derived" type="xsd:IDREFS"/>
		<xsd:attribute name="_instances" type="xsd:IDREFS"/>
		<xsd:attribute name="_desynched_atts" type="xsd:string"/>
		<xsd:attribute name="_real_archetype" type="xsd:boolean"/>
		<xsd:attribute name="_subtype" type="xsd:boolean"/>
	</xsd:complexType>

	<xsd:complexType name="ClassType">
		<xsd:sequence>
			<xsd:element name="Attribute" type="AttributeType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Constraint" type="ConstraintType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="ConstraintDefinition" type="ConstraintDefinitionType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="TaggedValue" type="TaggedValueType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="isAbstract" type="xsd:boolean" use="required"/>
		<xsd:attribute name="stereotype" type="xsd:string"/>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="from" type="xsd:string"/>
		<xsd:attribute name="childRoles" type="xsd:IDREFS"/>
		<xsd:attribute name="parentRoles" type="xsd:IDREFS"/>
		<xsd:attribute name="associationRoles" type="xsd:IDREFS"/>
		<xsd:attribute name="association" type="xsd:IDREF"/>
		<xsd:attribute name="subTypes" type="xsd:IDREFS"/>
		<xsd:attribute name="baseTypes" type="xsd:IDREFS"/>
		<xsd:attribute name="_id" type="xsd:ID"/>
		<xsd:attribute name="_archetype" type="xsd:IDREF"/>
		<xsd:attribute name="_derived" type="xsd:IDREFS"/>
		<xsd:attribute name="_instances" type="xsd:IDREFS"/>
		<xsd:attribute name="_desynched_atts" type="xsd:string"/>
		<xsd:attribute name="_real_archetype" type="xsd:boolean"/>
		<xsd:attribute name="_subtype" type="xsd:boolean"/>
	</xsd:complexType>

	<xsd:complexType name="DiagramType">
		<xsd:sequence>
			<xsd:element name="Association" type="AssociationType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Class" type="ClassType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Composition" type="CompositionType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Namespace" type="NamespaceType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Diagram" type="DiagramType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="version" type="xsd:string"/>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="_id" type="xsd:ID"/>
		<xsd:attribute name="_archetype" type="xsd:IDREF"/>
		<xsd:attribute name="_derived" type="xsd:IDREFS"/>
		<xsd:attribute name="_instances" type="xsd:IDREFS"/>
		<xsd:attribute name="_desynched_atts" type="xsd:string"/>
		<xsd:attribute name="_real_archetype" type="xsd:boolean"/>
		<xsd:attribute name="_subtype" type="xsd:boolean"/>
		<xsd:attribute name="_libname" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="AssociationType">
		<xsd:sequence>
			<xsd:element name="AssociationRole" type="AssociationRoleType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="TaggedValue" type="TaggedValueType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="nonpersistent" type="xsd:boolean" default="false"/>
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="assocClass" type="xsd:IDREF"/>
		<xsd:attribute name="_id" type="xsd:ID"/>
		<xsd:attribute name="_archetype" type="xsd:IDREF"/>
		<xsd:attribute name="_derived" type="xsd:IDREFS"/>
		<xsd:attribute name="_instances" type="xsd:IDREFS"/>
		<xsd:attribute name="_desynched_atts" type="xsd:string"/>
		<xsd:attribute name="_real_archetype" type="xsd:boolean"/>
		<xsd:attribute name="_subtype" type="xsd:boolean"/>
	</xsd:complexType>

	<xsd:complexType name="CompositionType">
		<xsd:sequence>
			<xsd:element name="CompositionChildRole" type="CompositionChildRoleType"/>
			<xsd:element name="CompositionParentRole" type="CompositionParentRoleType"/>
		</xsd:sequence>
		<xsd:attribute name="nonpersistent" type="xsd:boolean" default="false"/>
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="_id" type="xsd:ID"/>
		<xsd:attribute name="_archetype" type="xsd:IDREF"/>
		<xsd:attribute name="_derived" type="xsd:IDREFS"/>
		<xsd:attribute name="_instances" type="xsd:IDREFS"/>
		<xsd:attribute name="_desynched_atts" type="xsd:string"/>
		<xsd:attribute name="_real_archetype" type="xsd:boolean"/>
		<xsd:attribute name="_subtype" type="xsd:boolean"/>
	</xsd:complexType>

	<xsd:complexType name="NamespaceType">
		<xsd:sequence>
			<xsd:element name="Association" type="AssociationType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Class" type="ClassType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Composition" type="CompositionType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Namespace" type="NamespaceType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="_id" type="xsd:ID"/>
		<xsd:attribute name="_archetype" type="xsd:IDREF"/>
		<xsd:attribute name="_derived" type="xsd:IDREFS"/>
		<xsd:attribute name="_instances" type="xsd:IDREFS"/>
		<xsd:attribute name="_desynched_atts" type="xsd:string"/>
		<xsd:attribute name="_real_archetype" type="xsd:boolean"/>
		<xsd:attribute name="_subtype" type="xsd:boolean"/>
	</xsd:complexType>

	<xsd:complexType name="TaggedValueType">
		<xsd:attribute name="value" type="xsd:string"/>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="_id" type="xsd:ID"/>
		<xsd:attribute name="_archetype" type="xsd:IDREF"/>
		<xsd:attribute name="_derived" type="xsd:IDREFS"/>
		<xsd:attribute name="_instances" type="xsd:IDREFS"/>
		<xsd:attribute name="_desynched_atts" type="xsd:string"/>
		<xsd:attribute name="_real_archetype" type="xsd:boolean"/>
		<xsd:attribute name="_subtype" type="xsd:boolean"/>
	</xsd:complexType>

	<xsd:complexType name="ConstraintDefinitionType">
		<xsd:attribute name="stereotype" type="xsd:string" default="method"/>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="parameterList" type="xsd:string"/>
		<xsd:attribute name="expression" type="xsd:string" use="required"/>
		<xsd:attribute name="returnType" type="xsd:string" use="required"/>
		<xsd:attribute name="_id" type="xsd:ID"/>
		<xsd:attribute name="_archetype" type="xsd:IDREF"/>
		<xsd:attribute name="_derived" type="xsd:IDREFS"/>
		<xsd:attribute name="_instances" type="xsd:IDREFS"/>
		<xsd:attribute name="_desynched_atts" type="xsd:string"/>
		<xsd:attribute name="_real_archetype" type="xsd:boolean"/>
		<xsd:attribute name="_subtype" type="xsd:boolean"/>
	</xsd:complexType>

	<xsd:complexType name="AttributeType">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="type" type="xsd:string" use="required"/>
		<xsd:attribute name="defvalue" type="xsd:string"/>
		<xsd:attribute name="min" type="xsd:long" use="required"/>
		<xsd:attribute name="max" type="xsd:long" use="required"/>
		<xsd:attribute name="visibility" type="xsd:string" default="public"/>
		<xsd:attribute name="ordered" type="xsd:boolean" default="false"/>
		<xsd:attribute name="nonpersistent" type="xsd:boolean" default="false"/>
		<xsd:attribute name="registry" type="xsd:boolean" default="false"/>
		<xsd:attribute name="_id" type="xsd:ID"/>
		<xsd:attribute name="_archetype" type="xsd:IDREF"/>
		<xsd:attribute name="_derived" type="xsd:IDREFS"/>
		<xsd:attribute name="_instances" type="xsd:IDREFS"/>
		<xsd:attribute name="_desynched_atts" type="xsd:string"/>
		<xsd:attribute name="_real_archetype" type="xsd:boolean"/>
		<xsd:attribute name="_subtype" type="xsd:boolean"/>
	</xsd:complexType>

	<xsd:complexType name="ConstraintType">
		<xsd:attribute name="description" type="xsd:string"/>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="expression" type="xsd:string" use="required"/>
		<xsd:attribute name="_id" type="xsd:ID"/>
		<xsd:attribute name="_archetype" type="xsd:IDREF"/>
		<xsd:attribute name="_derived" type="xsd:IDREFS"/>
		<xsd:attribute name="_instances" type="xsd:IDREFS"/>
		<xsd:attribute name="_desynched_atts" type="xsd:string"/>
		<xsd:attribute name="_real_archetype" type="xsd:boolean"/>
		<xsd:attribute name="_subtype" type="xsd:boolean"/>
	</xsd:complexType>

 <xsd:element name="Diagram" type="DiagramType"/>

</xsd:schema>

=== ksmyth/UDM/etc/UdmProject_udm.xml
<Diagram name="UdmProject" version="1.00" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Uml.xsd">
	<Class _id="id5" name="Project" isAbstract="false" parentRoles="id6 id8 ida">
		<Attribute max="1" min="1" name="name" type="String" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
	</Class>
	<Class _id="id3" name="Datanetwork" childRoles="id4 id7 id9" isAbstract="false">
		<Attribute max="1" min="1" name="systemname" type="String" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
		<Attribute max="1" min="1" name="metaDgr" type="String" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
		<Attribute max="1" min="0" name="metalocator" type="String" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
	</Class>
	<Composition name="Composition" nonpersistent="false">
		<CompositionChildRole _id="id4" max="1" min="0" name="cross_associations" target="id3" isNavigable="true"/>
		<CompositionParentRole _id="id6" target="id5" isNavigable="true"/>
	</Composition>
	<Composition name="Composition" nonpersistent="false">
		<CompositionChildRole _id="id7" max="-1" min="0" name="instances" target="id3" isNavigable="true"/>
		<CompositionParentRole _id="id8" target="id5" isNavigable="true"/>
	</Composition>
	<Composition name="Composition" nonpersistent="false">
		<CompositionChildRole _id="id9" max="1" min="0" name="crosslinks" target="id3" isNavigable="true"/>
		<CompositionParentRole _id="ida" target="id5" isNavigable="true"/>
	</Composition>
</Diagram>

=== ksmyth/UDM/judm/build/build_win/TimeSeries/meta/TimeSeries_udm.xml
<Diagram name="TimeSeries" version="1.00" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Uml.xsd">
	<Association name="Association" nonpersistent="false">
		<AssociationRole _id="id11" max="-1" min="0" name="src_tp" target="id4" isPrimary="false" isNavigable="true"/>
		<AssociationRole _id="id12" max="-1" min="0" name="dst_dv" target="ide" isPrimary="false" isNavigable="true"/>
	</Association>
	<Association name="Association" nonpersistent="false">
		<AssociationRole _id="id13" max="-1" min="0" name="src" target="id4" isPrimary="false" isNavigable="true"/>
		<AssociationRole _id="id14" max="-1" min="0" name="dst" target="id8" isPrimary="false" isNavigable="true"/>
	</Association>
	<Class _id="id3" name="string_data" baseTypes="id4" isAbstract="false">
		<Attribute max="1" min="1" name="value" type="String" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
	</Class>
	<Class _id="id5" name="integer_data" baseTypes="id4" isAbstract="false">
		<Attribute max="1" min="1" name="value" type="Integer" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
	</Class>
	<Class _id="id6" name="real_data" baseTypes="id4" isAbstract="false">
		<Attribute max="1" min="1" name="value" type="Real" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
	</Class>
	<Class _id="id7" name="boolean_data" baseTypes="id4" isAbstract="false">
		<Attribute max="1" min="1" name="value" type="Boolean" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
	</Class>
	<Class _id="id8" name="data_label" childRoles="id9" isAbstract="false" associationRoles="id14">
		<Attribute max="1" min="0" name="name" type="String" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
	</Class>
	<Class _id="id4" name="data_value" subTypes="id3 id5 id6 id7" childRoles="idc" isAbstract="true" associationRoles="id11 id13"/>
	<Class _id="ida" name="Container" isAbstract="false" parentRoles="idb idd id10"/>
	<Class _id="ide" name="time_point" childRoles="idf" isAbstract="false" associationRoles="id12">
		<Attribute max="1" min="1" name="at" type="Real" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
	</Class>
	<Composition name="Composition" nonpersistent="false">
		<CompositionChildRole _id="id9" max="-1" min="0" target="id8" isNavigable="true"/>
		<CompositionParentRole _id="idb" target="ida" isNavigable="true"/>
	</Composition>
	<Composition name="Composition" nonpersistent="false">
		<CompositionChildRole _id="idc" max="-1" min="0" target="id4" isNavigable="true"/>
		<CompositionParentRole _id="idd" target="ida" isNavigable="true"/>
	</Composition>
	<Composition name="Composition" nonpersistent="false">
		<CompositionChildRole _id="idf" max="-1" min="0" target="ide" isNavigable="true"/>
		<CompositionParentRole _id="id10" target="ida" isNavigable="true"/>
	</Composition>
</Diagram>

=== ksmyth/UDM/judm/build/build_win/GeneTF/meta/GeneTF_udm.xml
<Diagram name="GeneTF" version="2.00" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Uml.xsd">
	<Namespace name="genetf">
		<Association _id="idd" name="Regulation" assocClass="id3" nonpersistent="false">
			<AssociationRole _id="ide" max="-1" min="0" name="gene" target="ida" isPrimary="false" isNavigable="true"/>
			<AssociationRole _id="idf" max="-1" min="0" name="tf" target="id7" isPrimary="false" isNavigable="true"/>
		</Association>
		<Class _id="id3" name="Regulation" childRoles="id4" isAbstract="false" association="idd">
			<Attribute max="1" min="1" name="type" type="Integer" ordered="false" defvalue="0;" registry="false" visibility="public" nonpersistent="false"/>
		</Class>
		<Class _id="id7" name="TF" childRoles="id8" isAbstract="false" associationRoles="idf">
			<Attribute max="1" min="1" name="name" type="String" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
		</Class>
		<Class _id="ida" name="Gene" childRoles="idb" isAbstract="false" associationRoles="ide">
			<Attribute max="1" min="1" name="name" type="String" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
		</Class>
		<Class _id="id5" name="Container" isAbstract="false" parentRoles="id6 id9 idc"/>
		<Composition name="Composition" nonpersistent="false">
			<CompositionChildRole _id="id4" max="-1" min="0" target="id3" isNavigable="true"/>
			<CompositionParentRole _id="id6" target="id5" isNavigable="true"/>
		</Composition>
		<Composition name="Composition" nonpersistent="false">
			<CompositionChildRole _id="id8" max="-1" min="0" target="id7" isNavigable="true"/>
			<CompositionParentRole _id="id9" target="id5" isNavigable="true"/>
		</Composition>
		<Composition name="Composition" nonpersistent="false">
			<CompositionChildRole _id="idb" max="-1" min="0" target="ida" isNavigable="true"/>
			<CompositionParentRole _id="idc" target="id5" isNavigable="true"/>
		</Composition>
	</Namespace>
</Diagram>

=== ksmyth/UDM/judm/build/build_win/GeneTRE/meta/GeneTRE_udm.xml
<Diagram name="GeneTRE" version="2.00" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Uml.xsd">
	<Namespace name="genetre">
		<Association name="Association" nonpersistent="false">
			<AssociationRole _id="id10" max="-1" min="0" name="tf" target="id7" isPrimary="false" isNavigable="true"/>
			<AssociationRole _id="id11" max="-1" min="0" name="bindsTo" target="ida" isPrimary="false" isNavigable="true"/>
		</Association>
		<Association _id="id12" name="TRE" assocClass="id3" nonpersistent="false">
			<AssociationRole _id="id13" max="-1" min="0" name="gene" target="idd" isPrimary="false" isNavigable="true"/>
			<AssociationRole _id="id14" max="-1" min="0" name="site" target="ida" isPrimary="false" isNavigable="true"/>
		</Association>
		<Class _id="id3" name="TRE" childRoles="id4" isAbstract="false" association="id12">
			<Attribute max="1" min="1" name="regulation" type="Integer" ordered="false" defvalue="0;" registry="false" visibility="public" nonpersistent="false"/>
			<Attribute max="1" min="1" name="position" type="Integer" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
			<Attribute max="1" min="1" name="strand" type="Boolean" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
			<Attribute max="1" min="1" name="coreScore" type="Real" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
			<Attribute max="1" min="1" name="matrixScore" type="Real" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
		</Class>
		<Class _id="id7" name="TF" childRoles="id8" isAbstract="false" associationRoles="id10">
			<Attribute max="1" min="1" name="name" type="String" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
		</Class>
		<Class _id="ida" name="PWM" childRoles="idb" isAbstract="false" associationRoles="id11 id14">
			<Attribute max="1" min="1" name="name" type="String" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
		</Class>
		<Class _id="idd" name="Gene" childRoles="ide" isAbstract="false" associationRoles="id13">
			<Attribute max="1" min="1" name="name" type="String" ordered="false" registry="false" visibility="public" nonpersistent="false"/>
		</Class>
		<Class _id="id5" name="Container" isAbstract="false" parentRoles="id6 id9 idc idf"/>
		<Composition name="Composition" nonpersistent="false">
			<CompositionChildRole _id="id4" max="-1" min="0" target="id3" isNavigable="true"/>
			<CompositionParentRole _id="id6" target="id5" isNavigable="true"/>
		</Composition>
		<Composition name="Composition" nonpersistent="false">
			<CompositionChildRole _id="id8" max="-1" min="0" target="id7" isNavigable="true"/>
			<CompositionParentRole _id="id9" target="id5" isNavigable="true"/>
		</Composition>
		<Composition name="Composition" nonpersistent="false">
			<CompositionChildRole _id="idb" max="-1" min="0" target="ida" isNavigable="true"/>
			<CompositionParentRole _id="idc" target="id5" isNavigable="true"/>
		</Composition>
		<Composition name="Composition" nonpersistent="false">
			<CompositionChildRole _id="ide" max="-1" min="0" target="idd" isNavigable="true"/>
			<CompositionParentRole _id="idf" target="id5" isNavigable="true"/>
		</Composition>
	</Namespace>
</Diagram>

=== ksmyth/UDM/etc/UdmProject.xml
<?xml version="1.0"?>

<Diagram name ="UdmProject"
   version="1.00"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="Uml.xsd">

   <!-- Generated by the UML2XML interpreter -->

<Class _id="id00007" name= "Datanetwork" isAbstract= "false" childRoles= " id00002 id00004 id00006" >
   <Attribute name= "systemname" type= "String" ordered= "false" visibility= "public" nonpersistent= "false" registry= "false" min= "1" max= "1"/>
   <Attribute name= "metaDgr" type= "String" ordered= "false" visibility= "public" nonpersistent= "false" registry= "false" min= "1" max= "1"/>
   <Attribute name= "metalocator" type= "String" ordered= "false" visibility= "public" nonpersistent= "false" registry= "false" min= "0" max= "1"/>
</Class>
<Class _id="id00008" name= "Project" isAbstract= "false" parentRoles= " id00001 id00003 id00005" >
   <Attribute name= "name" type= "String" ordered= "false" visibility= "public" nonpersistent= "false" registry= "false" min= "1" max= "1"/>
</Class>
<Composition>
   <CompositionChildRole _id= "id00002" name= "crosslinks" min= "0" max= "1" target= "id00007"/>
   <CompositionParentRole _id= "id00001" target= "id00008"/>
</Composition>
<Composition>
   <CompositionChildRole _id= "id00004" name= "instances" min= "0" max= "-1" target= "id00007"/>
   <CompositionParentRole _id= "id00003" target= "id00008"/>
</Composition>
<Composition>
   <CompositionChildRole _id= "id00006" name= "cross_associations" min= "0" max= "1" target= "id00007"/>
   <CompositionParentRole _id= "id00005" target= "id00008"/>
</Composition>
</Diagram>

=== ksmyth/UDM/tests/test_UdmPython/UdmPythonTestMeta.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Diagram name="UdmPythonTestMeta" version="1.00" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Uml.xsd">

  <Association _id="id17" assocClass="id7" name="Connection" nonpersistent="false">
    <AssociationRole _id="id18" isNavigable="true" isPrimary="false" max="-1" min="0" name="srcConnection" target="id6"/>
    <AssociationRole _id="id19" isNavigable="true" isPrimary="false" max="-1" min="0" name="dstConnection" target="id6"/>
  </Association>

  <Class _id="id3" baseTypes="id4" childRoles="idA id12" isAbstract="false" name="Container" parentRoles="id9 idB idD idF id11" stereotype="Model"/>

  <Class _id="id5" baseTypes="id4" childRoles="id10" isAbstract="false" name="AtomA" stereotype="Atom">
    <Attribute defvalue="false;" max="1" min="1" name="boolattr" nonpersistent="false" ordered="false" registry="false" type="Boolean" visibility="public"/>
    <Attribute max="1" min="1" name="stringattr" nonpersistent="false" ordered="false" registry="false" type="String" visibility="public"/>
    <Attribute max="1" min="1" name="intattr" nonpersistent="false" ordered="false" registry="false" type="Integer" visibility="public"/>
  </Class>

  <Class _id="id6" associationRoles="id18 id19" baseTypes="id4" childRoles="idC ide" isAbstract="false" name="AtomB" stereotype="Atom"/>

  <Class _id="id7" association="id17" baseTypes="id4" childRoles="id8" isAbstract="false" name="Connection" stereotype="Connection"/>

  <Class _id="id13" childRoles="id15" isAbstract="false" name="RootFolder" parentRoles="id14 id16" stereotype="Folder">
    <Attribute max="1" min="0" name="name" nonpersistent="false" ordered="false" registry="false" type="String" visibility="public"/>
  </Class>

  <Class _id="id4" isAbstract="true" name="MgaObject" subTypes="id3 id5 id6 id7">
    <Attribute max="1" min="0" name="name" nonpersistent="false" ordered="false" registry="false" type="String" visibility="public"/>
    <Attribute max="1" min="0" name="position" nonpersistent="false" ordered="false" registry="false" type="String" visibility="public"/>
  </Class>

  <Composition nonpersistent="false">
    <CompositionChildRole _id="id8" isNavigable="true" max="-1" min="0" target="id7"/>
    <CompositionParentRole _id="id9" isNavigable="true" target="id3"/>
  </Composition>

  <Composition nonpersistent="false">
    <CompositionChildRole _id="idA" isNavigable="true" max="-1" min="0" target="id3"/>
    <CompositionParentRole _id="idB" isNavigable="true" target="id3"/>
  </Composition>

  <Composition nonpersistent="false">
    <CompositionChildRole _id="idC" isNavigable="true" max="-1" min="0" name="cmproleA" target="id6"/>
    <CompositionParentRole _id="idD" isNavigable="true" target="id3"/>
  </Composition>

  <Composition nonpersistent="false">
    <CompositionChildRole _id="ide" isNavigable="true" max="-1" min="0" name="cmproleB" target="id6"/>
    <CompositionParentRole _id="idF" isNavigable="true" target="id3"/>
  </Composition>

  <Composition nonpersistent="false">
    <CompositionChildRole _id="id10" isNavigable="true" max="-1" min="0" target="id5"/>
    <CompositionParentRole _id="id11" isNavigable="true" target="id3"/>
  </Composition>

  <Composition nonpersistent="false">
    <CompositionChildRole _id="id12" isNavigable="true" max="-1" min="0" target="id3"/>
    <CompositionParentRole _id="id14" isNavigable="true" target="id13"/>
  </Composition>

  <Composition nonpersistent="false">
    <CompositionChildRole _id="id15" isNavigable="true" max="-1" min="0" target="id13"/>
    <CompositionParentRole _id="id16" isNavigable="true" target="id13"/>
  </Composition>

</Diagram>
